[package]
name = "smol-bf"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "smol-bf"

[dependencies.lightning-sys]
git = "https://github.com/petelliott/lightning-sys"
rev = "b8d2eb8"
optional = true

[features]
default = ["jit"]
jit = ["lightning-sys"]
